name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.10'
          - '5.12'
          - '5.14'
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install build-essential zlib1g-dev zlib1g libssl libssl-dev
        run: sudo apt -y install build-essential zlib1g-dev zlib1g libssl libssl-dev
      - name: perl -V
        run: perl -V
      - name: Install cpanm
        run: curl -L https://cpanmin.us | perl - App::cpanminus
      - name: Install Alien Stuff
        run: cpanm -n Alien::Build Alien::Base URI URI::Escape Mojo::DOM58 Alien::Autotools
      - name: Install Dependencies
        run: cpanm -n --installdeps .
      - name: Run Tests
        sudo: false
        run: |
          perl Makefile.PL
          make
          make test
